version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./Backend/tarzan
      args:
        SERVER_MODE: dev
    ports:
      - 8080:8080
  frontend:
    container_name: frontend
    build:
      context: ./Frontend/tarzan
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
      - ./frontend/tarzan:/usr/src/app
    stdin_open: true
    depends_on:
      - backend
