spring:
  datasource:
    url: jdbc:postgresql://15.164.163.207:5432/tarzan
    username: postgres
    password: '@tarzan_zxcvbnm1234'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    use_sql_comments: true
    database: postgresql


  data:
    redis:
      host: 15.164.163.207  # 또는 Redis 서버의 IP/도메인
      port: 6379
      password: strawberry_tarzan_8960!

      jedis:
        pool:
          max-active: 10  # 최대 커넥션 수
          max-idle: 5      # 최대 대기 커넥션 수
          min-idle: 1      # 최소 대기 커넥션 수
      timeout: 2000      # 타임아웃 시간 (ms)

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 47134587732-6gq6500f5srhmscdv8bektl4uovnqr3t.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: ${back.base-url}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          kakao:
            client-id: defea2136916c246b3e2f4db75b9d387
            client-secret: 3Y2ePu10MYyMaKT7kS1JvOLb5XXLagYi
            redirect-uri: ${back.base-url}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  web:
    resources:
      static-locations: classpath:/static

jwt:
  secret-key: f3ea5bb104ef3a66b65f87dacf67411fa982fdd62bc99da583d3cd37102ff435
  refresh-secret-key: f3ea5bb104ef3a66b65f87dacf67411fa982fdd62bc99da583d3cd37102ff434
  cookie-secure: false


api:
  vworld:
    real-estate:
      url:
        "http://api.vworld.kr/ned/data/getEBOfficeInfo"
      key:
        "EA6F08E6-F05D-380A-840A-709AF07229F4"
  data-seoul:
    url:
      "http://openapi.seoul.go.kr:8088"
    key:
      "655351685763686938367558756e6f"

front:
  base-url:  "http://localhost:5173"

back:
  base-url: "http://localhost:8080"

