FROM node:22.6.0-alpine as builder

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 의존성 설치
COPY package.json package-lock.json ./
RUN npm install

# 소스 코드 복사 및 Vite 빌드 실행
COPY . .
RUN npm run build

# 배포 단계: Nginx를 사용하여 빌드된 파일 서빙
FROM nginx:alpine

# 빌드된 파일을 Nginx의 웹 루트로 복사
COPY --from=builder /app/dist /usr/share/nginx/html

# 80번 포트로 서비스
EXPOSE 80

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
