spring:
  application:
    name: tarzan

  profiles:
    active: dev

jwt:
  access:
    expiration: 3600000  # 1시간
    header: Authorization
  refresh:
    expiration: 1209600000  # 2주
    header: Authorization-refresh



tarzan:
  data-truncate: false
  data-load:
    bicycle: false
    bus-stop: false
    cctv: false
    civic-center: false
    convenience-store: false
    gym: false
    hospital: false
    house: false
    mart: false
    medical-clinic: false
    park: false
    pharmacy: false
    police: false
    subway: false
