spring:
  application:
    name: tarzan

  datasource:
    url: jdbc:postgresql://54.180.109.0:5432/tarzan
    username: postgres
    password: '@tarzan_zxcvbnm123!'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    use_sql_comments: true
    database: postgresql

  batch:
    job:
#      name: ${job.name:NONE}
      enabled: true
    jdbc:
#      initialize-schema: never
       initialize-schema: always

  web:
    resources:
      static-locations: classpath:/static
